"""Topic CRUD, plan generation, build/improve/revert routes."""


from __future__ import annotations


import json


from typing import List


from fastapi import APIRouter, HTTPException, Request


import agent


from store import (
    BulkCreate,
    ConsolidateRequest,
    HashRequest,
    MetaPromptUpdate,
    PlanEdit,
    RefineRequest,
    State,
    Topic,
    TopicCreate,
    TopicUpdate,
    _common_path_prefix,
    _ensure_slug,
    _find,
    _lock,
    _work_dir,
    parse_topics,
    save_state,
    state,
)


from jobs import (
    _build_job,
    _consolidate_job,
    _improve_job,
    _log_get,
    _plan_job,
    _revert_job,
)


router = APIRouter()


@router.get("/api/state", response_model=State)
def get_state() -> State:
    return state


@router.put("/api/meta-prompt", response_model=State)
def update_meta_prompt(payload: MetaPromptUpdate) -> State:
    with _lock:
        state.metaPrompt = payload.metaPrompt
        save_state(state)
    return state


@router.post("/api/topics", response_model=Topic)
def create_topic(payload: TopicCreate) -> Topic:
    with _lock:
        topic = Topic(title=payload.title.strip())
        state.topics.append(topic)
        save_state(state)
    return topic


@router.post("/api/topics/bulk", response_model=List[Topic])
def create_topics_bulk(payload: BulkCreate) -> List[Topic]:
    """Split a pasted block of text into one topic card per line.

    Skips titles that already exist (case-insensitive) so re-pasting a list
    doesn't create duplicates. Returns only the newly created cards.
    """
    with _lock:
        existing = {t.title.strip().lower() for t in state.topics}
        created: List[Topic] = []
        for path, title, notes in parse_topics(payload.text):
            key = title.lower()
            if key in existing:
                continue
            existing.add(key)
            topic = Topic(title=title, notes=notes, path=path)
            state.topics.append(topic)
            created.append(topic)
        if created:
            save_state(state)
    return created


@router.delete("/api/topics")
def delete_all_topics() -> dict:
    with _lock:
        count = len(state.topics)
        state.topics = []
        save_state(state)
    return {"ok": True, "deleted": count}


@router.put("/api/topics/{topic_id}", response_model=Topic)
def update_topic(topic_id: str, payload: TopicUpdate) -> Topic:
    with _lock:
        for topic in state.topics:
            if topic.id == topic_id:
                data = payload.model_dump(exclude_none=True)
                for key, value in data.items():
                    setattr(topic, key, value)
                save_state(state)
                return topic
    raise HTTPException(status_code=404, detail="Topic not found")


@router.delete("/api/topics/{topic_id}")
def delete_topic(topic_id: str) -> dict:
    with _lock:
        before = len(state.topics)
        state.topics = [t for t in state.topics if t.id != topic_id]
        if len(state.topics) == before:
            raise HTTPException(status_code=404, detail="Topic not found")
        save_state(state)
    return {"ok": True}


@router.post("/api/plans/generate")
def generate_plans() -> dict:
    """Queue plan generation for every topic that doesn't have one yet."""
    with _lock:
        todo = [t for t in state.topics if t.planStatus in ("none", "error")]
        for topic in todo:
            topic.planStatus = "queued"
            topic.planError = ""
            _ensure_slug(topic)
        save_state(state)
        ids = [t.id for t in todo]
    for topic_id in ids:
        agent.EXECUTOR.submit(_plan_job, topic_id)
    return {"queued": len(ids), "concurrency": agent.CONCURRENCY}


@router.post("/api/topics/consolidate", response_model=Topic)
def consolidate_topics(payload: ConsolidateRequest) -> Topic:
    """Merge several plan-ready topics into one synthesized plan.

    Only applies to topics still in plan mode (status ``ready`` with a plan).
    Creates a new topic whose plan is generated by the agent; the sources are
    removed once the merge succeeds (handled in the background job).
    """
    with _lock:
        sources = [t for t in (_find(i) for i in payload.ids) if t]
        if len(sources) < 2:
            raise HTTPException(status_code=400, detail="Select at least two plans to consolidate")
        for t in sources:
            if t.planStatus != "ready" or not t.plan.strip():
                raise HTTPException(
                    status_code=400,
                    detail="Every selected topic must have a ready plan (still in plan mode)",
                )
        path = _common_path_prefix([t.path for t in sources])
        joined = " | ".join(t.title for t in sources)
        new = Topic(
            title=f"Merging Topics: {joined}"[:120],
            planStatus="queued",
            path=path,
        )
        state.topics.append(new)
        _ensure_slug(new)
        src_plans = [(t.title, t.plan) for t in sources]
        src_ids = [t.id for t in sources]
        meta = state.metaPrompt
        save_state(state)
    agent.EXECUTOR.submit(_consolidate_job, new.id, src_plans, src_ids, meta)
    return new


@router.post("/api/topics/{topic_id}/plan", response_model=Topic)
def generate_one_plan(topic_id: str) -> Topic:
    """(Re)generate a single plan from scratch."""
    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        topic.planStatus = "queued"
        topic.planError = ""
        topic.sessionId = ""  # fresh session for a from-scratch regenerate
        _ensure_slug(topic)
        save_state(state)
    agent.EXECUTOR.submit(_plan_job, topic_id)
    return topic


@router.post("/api/topics/{topic_id}/plan/refine", response_model=Topic)
def refine_plan(topic_id: str, payload: RefineRequest) -> Topic:
    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        if not topic.plan:
            raise HTTPException(status_code=400, detail="No plan to refine yet")
        topic.planStatus = "queued"
        topic.planError = ""
        save_state(state)
    agent.EXECUTOR.submit(_plan_job, topic_id, payload.prompt)
    return topic


@router.put("/api/topics/{topic_id}/plan", response_model=Topic)
def edit_plan(topic_id: str, payload: PlanEdit) -> Topic:
    """Save a human's manual edits to the plan (also written to disk)."""
    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        topic.plan = payload.plan
        if topic.planStatus in ("none", "error"):
            topic.planStatus = "ready"
        slug = _ensure_slug(topic)
        save_state(state)
    (agent.topic_dir(slug) / agent.PLAN_FILE).write_text(payload.plan)
    return topic


@router.post("/api/topics/{topic_id}/build", response_model=Topic)
async def build_topic(topic_id: str, request: Request) -> Topic:
    # Parse body loosely so older clients that POST with an empty body still work.
    build_budget_usd: object = agent._BUDGET_UNSET
    try:
        raw = await request.body()
        if raw and raw.strip() and raw.strip() not in (b"null", b"undefined"):
            data = json.loads(raw)
            if isinstance(data, dict) and "budgetUsd" in data:
                build_budget_usd = data.get("budgetUsd")
    except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
        pass

    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        if not topic.plan:
            raise HTTPException(status_code=400, detail="Approve a plan first")
        topic.planStatus = "building"
        topic.planError = ""
        save_state(state)
    agent.EXECUTOR.submit(_build_job, topic_id, build_budget_usd)
    return topic


@router.post("/api/topics/{topic_id}/improve", response_model=Topic)
def improve_topic(topic_id: str, payload: RefineRequest) -> Topic:
    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        if topic.planStatus != "built":
            raise HTTPException(status_code=400, detail="Build the concept first")
        topic.planStatus = "building"
        topic.planError = ""
        save_state(state)
    agent.EXECUTOR.submit(_improve_job, topic_id, payload.prompt)
    return topic


@router.get("/api/topics/{topic_id}/history")
def topic_history(topic_id: str) -> dict:
    with _lock:
        topic = _find(topic_id)
        if not topic or not topic.slug:
            raise HTTPException(status_code=404, detail="Topic not found")
    cwd = _work_dir(topic)
    return {"commits": agent.git_log(cwd), "served": agent.served_hash(cwd)}


@router.post("/api/topics/{topic_id}/revert", response_model=Topic)
def revert_topic(topic_id: str, payload: HashRequest) -> Topic:
    with _lock:
        topic = _find(topic_id)
        if not topic:
            raise HTTPException(status_code=404, detail="Topic not found")
        if topic.planStatus != "built":
            raise HTTPException(status_code=400, detail="Nothing built to revert")
        topic.planStatus = "building"
        topic.planError = ""
        save_state(state)
    agent.EXECUTOR.submit(_revert_job, topic_id, payload.hash)
    return topic


@router.get("/api/topics/{topic_id}/log")
def get_log(topic_id: str) -> dict:
    """Live progress lines streamed from the topic's Grok run."""
    with _lock:
        topic = _find(topic_id)
        status = topic.planStatus if topic else "none"
    return {"status": status, "lines": _log_get(topic_id)}
